"""
Dome-World Command-Line Interface

Standard CLI entry-point designed for local testing and later integration
with IDE clients or MCP (Model Context Protocol) hosts.

The interface deliberately stays thin: it wires models → telemetry store
→ optional GitHub publisher. No business logic lives here; everything
is delegated so the same functions can be called programmatically.

Usage examples:
    python -m dome_world.cli demo --dry-run
    python -m dome_world.cli log --event swarm-pulse --bots 3
    python -m dome_world.cli post --log-id <uuid> --dry-run
"""

from __future__ import annotations

import argparse
import logging
import os
import random
import sys
from typing import List

from .models import BotState, SpatialLog, SwarmPhase
from .telemetry import TelemetryStore
from .github_client import GitHubLandingBoard
from .notation import RELEASE, chain, released

logger = logging.getLogger("dome_world")


def _configure_logging(verbose: bool = False) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s │ %(levelname)-7s │ %(name)s │ %(message)s",
        datefmt="%H:%M:%S",
    )


def _random_bot(bot_id: str) -> BotState:
    """Generate a plausible synthetic BotState for demos / testing."""
    phases = list(SwarmPhase)
    return BotState(
        bot_id=bot_id,
        phase=random.choice(phases),
        position=(
            round(random.uniform(-50, 50), 2),
            round(random.uniform(-50, 50), 2),
            round(random.uniform(0, 20), 2),
        ),
        velocity=(
            round(random.uniform(-2, 2), 2),
            round(random.uniform(-2, 2), 2),
            round(random.uniform(-0.5, 0.5), 2),
        ),
        influence_radius=round(random.uniform(0.5, 5.0), 2),
        metadata={"synthetic": True, "source": "cli-demo"},
    )


def cmd_demo(args: argparse.Namespace) -> int:
    """
    End-to-end local demonstration:
    1. Create synthetic bot states
    2. Record a SpatialLog
    3. Render an Observation
    4. (Optionally) post to The Landing Board in dry-run mode
    """
    store = TelemetryStore(data_dir=args.data_dir)

    bots: List[BotState] = [_random_bot(f"bot-{i:03d}") for i in range(args.bots)]
    for b in bots:
        store.write_state(b)

    log = SpatialLog(
        event_type="swarm-pulse",
        bot_states=bots,
        spatial_context={
            "flow_core_version": "0.1",
            "region": "alpha-sector",
            "passive_mode": True,
        },
        notes=(
            "Synthetic swarm pulse generated by the local CLI. "
            "All coordinates are illustrative; no live bots were harmed."
        ),
    )
    store.write_log(log)

    obs = store.create_observation_from_log(log)
    store.write_observation(obs)

    print("\n── Rendered Observation (Markdown) ──\n")
    print(obs.body_markdown)
    print("─────────────────────────────────────\n")

    if args.post or args.dry_run:
        board = GitHubLandingBoard(
            owner=args.owner,
            repo=args.repo,
            issue_number=args.issue,
            token=os.getenv("GITHUB_TOKEN"),
        )
        result = board.post_observation(obs, dry_run=args.dry_run or not args.post)
        print("GitHub response:", result)

    print(f"Local data written under: {store.data_dir.resolve()}")
    return 0


def cmd_log(args: argparse.Namespace) -> int:
    """Record a new SpatialLog from supplied parameters (or synthetic bots)."""
    store = TelemetryStore(data_dir=args.data_dir)

    if args.bots is not None:
        bots = [_random_bot(f"bot-{i:03d}") for i in range(args.bots)]
    else:
        # Attempt to load existing states
        bot_ids = store.list_bots()
        if not bot_ids:
            print("No existing bot states found and --bots not specified.", file=sys.stderr)
            return 1
        bots = []
        for bid in bot_ids:
            state = store.read_state(bid)
            if state:
                bots.append(state)

    log = SpatialLog(
        event_type=args.event,
        bot_states=bots,
        notes=args.notes or "",
        spatial_context={"source": "cli", "passive": True},
    )
    path = store.write_log(log)
    print(f"Recorded SpatialLog {log.log_id} → {path}")
    return 0


def cmd_post(args: argparse.Namespace) -> int:
    """Post an existing SpatialLog to The Landing Board."""
    store = TelemetryStore(data_dir=args.data_dir)
    log = store.read_log(args.log_id)
    obs = store.create_observation_from_log(log)

    board = GitHubLandingBoard(
        owner=args.owner,
        repo=args.repo,
        issue_number=args.issue,
        token=os.getenv("GITHUB_TOKEN"),
    )
    result = board.post_observation(obs, dry_run=args.dry_run)
    print(result)
    return 0


def cmd_trace(args: argparse.Namespace) -> int:
    """
    Read every SpatialLog in time order and write the movement as one
    Flow-Core chain. 出 is inserted where the swarm spread outward between
    two readings.
    """
    store = TelemetryStore(data_dir=args.data_dir)
    logs = [log for log in store.logs_in_order() if log.metrics]
    if not logs:
        print("No SpatialLogs with bot states recorded yet.", file=sys.stderr)
        return 1

    readings: List[str] = []
    previous = None
    for log in logs:
        m = log.metrics
        if previous is not None and released(previous.dispersion, m.dispersion):
            readings.append(RELEASE)
        readings.append(m.reading.notation if m.reading else "")
        stamp = log.created_at.strftime("%Y-%m-%d %H:%M:%S")
        print(f"{stamp}  {log.log_id[:8]}  {m.reading.notation or '(level)'}"
              f"  dispersion {m.dispersion:.3f}")
        previous = m

    last = logs[-1].metrics
    print()
    print("Chain:", chain(readings) or "(no vertical movement recorded)")
    if last.reading and last.reading.open_question:
        print("？    :", last.reading.open_question)
    cx, cy, cz = last.centroid
    fx, fy, fz = last.net_flow
    print(f"Next  : if the current flow holds for one time unit, the centroid moves "
          f"to ({cx + fx:.2f}, {cy + fy:.2f}, {cz + fz:.2f})")
    return 0


def cmd_list(args: argparse.Namespace) -> int:
    """List recorded logs and known bots."""
    store = TelemetryStore(data_dir=args.data_dir)
    print("Known bots :", store.list_bots() or "(none)")
    print("SpatialLogs:", store.list_logs() or "(none)")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="dome_world",
        description="Dome-World local telemetry & Landing Board utility",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Enable debug logging")
    parser.add_argument(
        "--data-dir",
        default="./dome_data",
        help="Directory for local telemetry storage (default: ./dome_data)",
    )

    sub = parser.add_subparsers(dest="command", required=True)

    # demo
    p_demo = sub.add_parser("demo", help="Run an end-to-end synthetic demonstration")
    p_demo.add_argument("--bots", type=int, default=3, help="Number of synthetic bots")
    p_demo.add_argument("--post", action="store_true", help="Actually post to GitHub (requires token)")
    p_demo.add_argument("--dry-run", action="store_true", help="Simulate GitHub post without network")
    p_demo.add_argument("--owner", default="miigwech-potato", help="GitHub repository owner")
    p_demo.add_argument("--repo", default="dome-world-hive", help="GitHub repository name")
    p_demo.add_argument("--issue", type=int, default=1, help="Landing Board issue number")
    p_demo.set_defaults(func=cmd_demo)

    # log
    p_log = sub.add_parser("log", help="Record a new SpatialLog")
    p_log.add_argument("--event", default="manual-observation", help="Event type label")
    p_log.add_argument("--bots", type=int, help="Generate N synthetic bots (else use stored states)")
    p_log.add_argument("--notes", default="", help="Free-text notes attached to the log")
    p_log.set_defaults(func=cmd_log)

    # post
    p_post = sub.add_parser("post", help="Post an existing SpatialLog to The Landing Board")
    p_post.add_argument("--log-id", required=True, help="UUID of the SpatialLog to publish")
    p_post.add_argument("--dry-run", action="store_true", help="Simulate the post")
    p_post.add_argument("--owner", default="miigwech-potato")
    p_post.add_argument("--repo", default="dome-world-hive")
    p_post.add_argument("--issue", type=int, default=1)
    p_post.set_defaults(func=cmd_post)

    # trace
    p_trace = sub.add_parser("trace", help="Write all logs as one Flow-Core chain, in time order")
    p_trace.set_defaults(func=cmd_trace)

    # list
    p_list = sub.add_parser("list", help="List known bots and SpatialLogs")
    p_list.set_defaults(func=cmd_list)

    return parser


def main(argv: List[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    _configure_logging(args.verbose)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
